# The VxEngine Project
# RTL drop targets


COMMIT_HASH := $(shell git rev-parse --short HEAD)
BUNDLE_NAME := vxengine-rtl-$(COMMIT_HASH)


.PHONY: drop
drop:
	mkdir $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_client_params.vh           $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_config.vh                  $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_ctrl_unit_cmds.vh          $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_intr_params.vh             $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_regio_params.vh            $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/include/vxe_vpu_regidx_params.vh       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/fifo/src/vxe_fifo.v                        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/fifo/src/vxe_fifo_2.v                      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/fifo2wxw/src/vxe_fifo2wxw.v                $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/pipe/src/vxe_pipe_2.v                      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/reg/src/vxe_reg_rst.v                      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/reg/src/vxe_reg.v                          $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_alignr.v                       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_iadd.v                         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_imult_stage.v                  $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_norm.v                         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_pack.v                         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_round.v                        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_shlpad.v                       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_shrjam.v                       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp_unpack.v                       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/flp/src/flp32_mac_5stg.v                   $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/relu/src/flp_relu.v                        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/relu/src/flp32_relu.v                      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/axi/src/vxe_axi4mas_biu.v                  $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/axi/src/vxe_axi4slv_biu.v                  $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txnid_codec/src/vxe_txnid_coder.v      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txnid_codec/src/vxe_txnid_decoder.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnreq_coder.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnreqa_coder.v      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnreqa_decoder.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnreqd_decoder.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnress_coder.v      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/txn_codec/src/vxe_txnress_decoder.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/axi_switch/src/vxe_axi_switch_us.v     $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/axi_switch/src/vxe_axi_switch_ds.v     $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/axi_switch/src/vxe_axi_switch.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/regio/src/vxe_regio.v                  $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/intr_unit/src/vxe_intr_unit.v          $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_cu_ds.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_cu_us.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_mas_ds.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_mas_us.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_vpu_ds.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub_vpu_us.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/mem_hub/src/vxe_mem_hub.v              $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_cmd_decoder.v     $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_dispatch_unit.v   $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_exec_unit.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_fetch_unit.v      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_intr_flt_unit.v   $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_cu_vpu_fwd_unit.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/ctrl_unit/src/vxe_ctrl_unit.v          $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_actf_ecu.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_actf_eu.v         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_cmd_dispatch.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_cmd_queue.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_lsu.v             $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_ecu.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_eu_agen.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_eu_fmac.v    $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_eu_rq_disp.v $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_eu_rs_dist.v $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_prod_eu.v         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_regu_ecu.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_rf.v              $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_stor_ecu.v        $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_stor_eu.v         $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vpu_thread_rf.v       $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vec_unit.v            $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/vec_unit/src/vxe_vec_unit_dummy.v      $(BUNDLE_NAME)
	cp $(VXENGINE_HOME)/hw/vxe/top/src/vxe_top.v                      $(BUNDLE_NAME)
	tar czf $(BUNDLE_NAME).tar.gz $(BUNDLE_NAME)


.PHONY: rmdrop
rmdrop:
	-rm -Rf vxengine-rtl-*
